"""
Vehicle Data Configuration
Contains sample vehicle data for demo purposes
Feature names MUST match exactly with training data column names
"""

vehicles_data = {
    "VIN 1WTSTUXX001111111": {
        "name": "Tesla Model 3 Performance",
        "type": "EV",
        # EV Range features
        "SoC": 85,
        "SoH": 90,
        "Battery_Voltage": 400,
        "Battery_Temperature": 25,
        "Driving_Speed": 60,
        "Load_Weight": 1500,
        "Ambient_Temperature": 20,
        # Oil (N/A for EV but needed for structure)
        "Engine_Temperature": 0,
        "Engine_RPM": 0,
        "Distance_Since_Last_Change": 0,
        "Oil_Viscosity": 0,
        "Idle_Time": 15,
        # Tire features
        "Total_Distance": 35000,
        "Average_Speed": 65,
        "Tire_Pressure": 32,
        "Road_Type": 1,
        "Alignment_Score": 92,
        "Tire_Age_Months": 24,
        "Harsh_Braking_Events": 45,
        "Temperature_Range": 25,
        # Brake features
        "Distance_Since_Last_Replacement": 28000,
        "Brake_Events_Per_100km": 85,
        "Driving_Style": 1,
        "Mountain_Driving_Percent": 10,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 120,
        # Battery degradation features
        "Battery_Age_Months": 36,
        "Total_Charge_Cycles": 450,
        "Fast_Charge_Percentage": 35,
        "Average_Depth_of_Discharge": 60,
        "Battery_Temperature_Avg": 25,
        "Battery_Temperature_Range": 15,
        "Idle_Time_Percentage": 12,
        "High_Speed_Percentage": 25,
        # Coolant features
        "Coolant_Age_Months": 24,
        "Engine_Temperature_Avg": 0,
        "Engine_Temperature_Max": 0,
        "Coolant_Level": 95,
        "Heavy_Load_Percentage": 15,
        "Coolant_pH": 9.2,
        # Air filter features
        "Distance_Since_Filter_Change": 12000,
        "Air_Quality_Index": 65,
        "Dusty_Road_Percentage": 15,
        "Urban_Driving_Percentage": 70,
        "Engine_Air_Flow": 95,
        "Humidity_Avg": 55,
        "Filter_Type": 1,
        # Transmission features
        "Distance_Since_Fluid_Change": 0,
        "Transmission_Temperature": 0,
        "Gear_Shifts_Per_100km": 0,
        "Harsh_Acceleration_Events": 25,
        "Towing_Percentage": 5,
        "City_Driving_Percentage": 70,
        "Transmission_Type": 0,
    },
    "VIN 1WTSTUXX001111112": {
        "name": "BMW i4 eDrive40",
        "type": "EV",
        "SoC": 50,
        "SoH": 85,
        "Battery_Voltage": 390,
        "Battery_Temperature": 30,
        "Driving_Speed": 80,
        "Load_Weight": 1400,
        "Ambient_Temperature": 18,
        "Engine_Temperature": 0,
        "Engine_RPM": 0,
        "Distance_Since_Last_Change": 0,
        "Oil_Viscosity": 0,
        "Idle_Time": 20,
        "Total_Distance": 52000,
        "Average_Speed": 75,
        "Tire_Pressure": 30,
        "Road_Type": 2,
        "Alignment_Score": 78,
        "Tire_Age_Months": 38,
        "Harsh_Braking_Events": 88,
        "Temperature_Range": 28,
        "Distance_Since_Last_Replacement": 45000,
        "Brake_Events_Per_100km": 120,
        "Driving_Style": 2,
        "Mountain_Driving_Percent": 25,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 180,
        "Battery_Age_Months": 48,
        "Total_Charge_Cycles": 680,
        "Fast_Charge_Percentage": 55,
        "Average_Depth_of_Discharge": 75,
        "Battery_Temperature_Avg": 28,
        "Battery_Temperature_Range": 22,
        "Idle_Time_Percentage": 18,
        "High_Speed_Percentage": 40,
        "Coolant_Age_Months": 36,
        "Engine_Temperature_Avg": 0,
        "Engine_Temperature_Max": 0,
        "Coolant_Level": 88,
        "Heavy_Load_Percentage": 20,
        "Coolant_pH": 8.8,
        "Distance_Since_Filter_Change": 18000,
        "Air_Quality_Index": 85,
        "Dusty_Road_Percentage": 20,
        "Urban_Driving_Percentage": 60,
        "Engine_Air_Flow": 88,
        "Humidity_Avg": 62,
        "Filter_Type": 1,
        "Distance_Since_Fluid_Change": 0,
        "Transmission_Temperature": 0,
        "Gear_Shifts_Per_100km": 0,
        "Harsh_Acceleration_Events": 45,
        "Towing_Percentage": 8,
        "City_Driving_Percentage": 60,
        "Transmission_Type": 0,
    },
    "VIN 1WTSTUXX001111113": {
        "name": "Audi e-tron GT",
        "type": "EV",
        "SoC": 65,
        "SoH": 88,
        "Battery_Voltage": 395,
        "Battery_Temperature": 22,
        "Driving_Speed": 70,
        "Load_Weight": 1600,
        "Ambient_Temperature": 21,
        "Engine_Temperature": 0,
        "Engine_RPM": 0,
        "Distance_Since_Last_Change": 0,
        "Oil_Viscosity": 0,
        "Idle_Time": 10,
        "Total_Distance": 28000,
        "Average_Speed": 68,
        "Tire_Pressure": 33,
        "Road_Type": 0,
        "Alignment_Score": 95,
        "Tire_Age_Months": 18,
        "Harsh_Braking_Events": 32,
        "Temperature_Range": 20,
        "Distance_Since_Last_Replacement": 22000,
        "Brake_Events_Per_100km": 65,
        "Driving_Style": 0,
        "Mountain_Driving_Percent": 5,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 95,
        "Battery_Age_Months": 28,
        "Total_Charge_Cycles": 320,
        "Fast_Charge_Percentage": 25,
        "Average_Depth_of_Discharge": 55,
        "Battery_Temperature_Avg": 23,
        "Battery_Temperature_Range": 12,
        "Idle_Time_Percentage": 8,
        "High_Speed_Percentage": 30,
        "Coolant_Age_Months": 18,
        "Engine_Temperature_Avg": 0,
        "Engine_Temperature_Max": 0,
        "Coolant_Level": 98,
        "Heavy_Load_Percentage": 10,
        "Coolant_pH": 9.5,
        "Distance_Since_Filter_Change": 8000,
        "Air_Quality_Index": 45,
        "Dusty_Road_Percentage": 8,
        "Urban_Driving_Percentage": 50,
        "Engine_Air_Flow": 98,
        "Humidity_Avg": 48,
        "Filter_Type": 1,
        "Distance_Since_Fluid_Change": 0,
        "Transmission_Temperature": 0,
        "Gear_Shifts_Per_100km": 0,
        "Harsh_Acceleration_Events": 18,
        "Towing_Percentage": 2,
        "City_Driving_Percentage": 50,
        "Transmission_Type": 0,
    },
    "VIN 1WTSTUXX001111114": {
        "name": "Mercedes EQS 450+",
        "type": "EV",
        "SoC": 90,
        "SoH": 92,
        "Battery_Voltage": 410,
        "Battery_Temperature": 24,
        "Driving_Speed": 50,
        "Load_Weight": 1450,
        "Ambient_Temperature": 19,
        "Engine_Temperature": 0,
        "Engine_RPM": 0,
        "Distance_Since_Last_Change": 0,
        "Oil_Viscosity": 0,
        "Idle_Time": 18,
        "Total_Distance": 18000,
        "Average_Speed": 55,
        "Tire_Pressure": 34,
        "Road_Type": 1,
        "Alignment_Score": 98,
        "Tire_Age_Months": 12,
        "Harsh_Braking_Events": 22,
        "Temperature_Range": 18,
        "Distance_Since_Last_Replacement": 15000,
        "Brake_Events_Per_100km": 55,
        "Driving_Style": 0,
        "Mountain_Driving_Percent": 3,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 85,
        "Battery_Age_Months": 18,
        "Total_Charge_Cycles": 210,
        "Fast_Charge_Percentage": 20,
        "Average_Depth_of_Discharge": 50,
        "Battery_Temperature_Avg": 22,
        "Battery_Temperature_Range": 10,
        "Idle_Time_Percentage": 10,
        "High_Speed_Percentage": 15,
        "Coolant_Age_Months": 12,
        "Engine_Temperature_Avg": 0,
        "Engine_Temperature_Max": 0,
        "Coolant_Level": 100,
        "Heavy_Load_Percentage": 5,
        "Coolant_pH": 9.3,
        "Distance_Since_Filter_Change": 5000,
        "Air_Quality_Index": 35,
        "Dusty_Road_Percentage": 5,
        "Urban_Driving_Percentage": 60,
        "Engine_Air_Flow": 99,
        "Humidity_Avg": 50,
        "Filter_Type": 1,
        "Distance_Since_Fluid_Change": 0,
        "Transmission_Temperature": 0,
        "Gear_Shifts_Per_100km": 0,
        "Harsh_Acceleration_Events": 12,
        "Towing_Percentage": 0,
        "City_Driving_Percentage": 60,
        "Transmission_Type": 0,
    },
    "VIN 1WTSTUXX001111115": {
        "name": "Porsche Taycan Turbo S",
        "type": "EV",
        "SoC": 40,
        "SoH": 80,
        "Battery_Voltage": 380,
        "Battery_Temperature": 28,
        "Driving_Speed": 95,
        "Load_Weight": 1550,
        "Ambient_Temperature": 22,
        "Engine_Temperature": 0,
        "Engine_RPM": 0,
        "Distance_Since_Last_Change": 0,
        "Oil_Viscosity": 0,
        "Idle_Time": 8,
        "Total_Distance": 68000,
        "Average_Speed": 85,
        "Tire_Pressure": 29,
        "Road_Type": 2,
        "Alignment_Score": 72,
        "Tire_Age_Months": 42,
        "Harsh_Braking_Events": 105,
        "Temperature_Range": 32,
        "Distance_Since_Last_Replacement": 55000,
        "Brake_Events_Per_100km": 145,
        "Driving_Style": 2,
        "Mountain_Driving_Percent": 30,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 210,
        "Battery_Age_Months": 60,
        "Total_Charge_Cycles": 850,
        "Fast_Charge_Percentage": 65,
        "Average_Depth_of_Discharge": 85,
        "Battery_Temperature_Avg": 30,
        "Battery_Temperature_Range": 25,
        "Idle_Time_Percentage": 5,
        "High_Speed_Percentage": 55,
        "Coolant_Age_Months": 48,
        "Engine_Temperature_Avg": 0,
        "Engine_Temperature_Max": 0,
        "Coolant_Level": 82,
        "Heavy_Load_Percentage": 35,
        "Coolant_pH": 8.5,
        "Distance_Since_Filter_Change": 22000,
        "Air_Quality_Index": 95,
        "Dusty_Road_Percentage": 28,
        "Urban_Driving_Percentage": 45,
        "Engine_Air_Flow": 82,
        "Humidity_Avg": 68,
        "Filter_Type": 1,
        "Distance_Since_Fluid_Change": 0,
        "Transmission_Temperature": 0,
        "Gear_Shifts_Per_100km": 0,
        "Harsh_Acceleration_Events": 75,
        "Towing_Percentage": 12,
        "City_Driving_Percentage": 45,
        "Transmission_Type": 0,
    },
    "VIN 1WTSTUXX001111116": {
        "name": "Toyota Camry Hybrid",
        "type": "Hybrid",
        "SoC": 75,
        "SoH": 88,
        "Battery_Voltage": 245,
        "Battery_Temperature": 26,
        "Driving_Speed": 65,
        "Load_Weight": 1520,
        "Ambient_Temperature": 21,
        "Engine_Temperature": 92,
        "Engine_RPM": 2200,
        "Distance_Since_Last_Change": 7500,
        "Oil_Viscosity": 5.0,
        "Idle_Time": 22,
        "Total_Distance": 42000,
        "Average_Speed": 62,
        "Tire_Pressure": 32,
        "Road_Type": 1,
        "Alignment_Score": 88,
        "Tire_Age_Months": 28,
        "Harsh_Braking_Events": 52,
        "Temperature_Range": 24,
        "Distance_Since_Last_Replacement": 35000,
        "Brake_Events_Per_100km": 95,
        "Driving_Style": 1,
        "Mountain_Driving_Percent": 12,
        "Regenerative_Braking": 1,
        "Brake_Temperature_Avg": 135,
        "Battery_Age_Months": 40,
        "Total_Charge_Cycles": 520,
        "Fast_Charge_Percentage": 0,
        "Average_Depth_of_Discharge": 45,
        "Battery_Temperature_Avg": 26,
        "Battery_Temperature_Range": 14,
        "Idle_Time_Percentage": 15,
        "High_Speed_Percentage": 22,
        "Coolant_Age_Months": 30,
        "Engine_Temperature_Avg": 90,
        "Engine_Temperature_Max": 98,
        "Coolant_Level": 92,
        "Heavy_Load_Percentage": 18,
        "Coolant_pH": 9.0,
        "Distance_Since_Filter_Change": 11000,
        "Air_Quality_Index": 70,
        "Dusty_Road_Percentage": 18,
        "Urban_Driving_Percentage": 65,
        "Engine_Air_Flow": 92,
        "Humidity_Avg": 58,
        "Filter_Type": 0,
        "Distance_Since_Fluid_Change": 38000,
        "Transmission_Temperature": 88,
        "Gear_Shifts_Per_100km": 180,
        "Harsh_Acceleration_Events": 28,
        "Towing_Percentage": 5,
        "City_Driving_Percentage": 65,
        "Transmission_Type": 2,
    },
}

# Feature mappings - MUST match exactly with training data column names
feature_mappings = {
    'ev_range': ['SoC', 'SoH', 'Battery_Voltage', 'Battery_Temperature', 
                 'Driving_Speed', 'Load_Weight', 'Ambient_Temperature'],
    
    'oil_life': ['Engine_Temperature', 'Engine_RPM', 'Load_Weight', 
                 'Distance_Since_Last_Change', 'Oil_Viscosity', 
                 'Ambient_Temperature', 'Idle_Time'],
    
    'tire_wear': ['Total_Distance', 'Average_Speed', 'Tire_Pressure', 
                  'Load_Weight', 'Road_Type', 'Alignment_Score', 
                  'Tire_Age_Months', 'Harsh_Braking_Events', 'Temperature_Range'],
    
    'brake_pad': ['Total_Distance', 'Distance_Since_Last_Replacement', 
                  'Average_Speed', 'Brake_Events_Per_100km', 'Load_Weight', 
                  'Driving_Style', 'Mountain_Driving_Percent', 
                  'Regenerative_Braking', 'Brake_Temperature_Avg'],
    
    'battery_degradation': ['Battery_Age_Months', 'Total_Charge_Cycles', 
                           'Fast_Charge_Percentage', 'Average_Depth_of_Discharge', 
                           'Battery_Temperature_Avg', 'Battery_Temperature_Range', 
                           'Total_Distance', 'Idle_Time_Percentage', 
                           'High_Speed_Percentage'],
    
    'coolant_health': ['Coolant_Age_Months', 'Engine_Temperature_Avg', 
                      'Engine_Temperature_Max', 'Coolant_Level', 
                      'Total_Distance', 'Heavy_Load_Percentage', 
                      'Ambient_Temperature', 'Idle_Time_Percentage', 'Coolant_pH'],
    
    'air_filter': ['Distance_Since_Filter_Change', 'Air_Quality_Index', 
                   'Dusty_Road_Percentage', 'Urban_Driving_Percentage', 
                   'Engine_Air_Flow', 'Idle_Time_Percentage', 
                   'Humidity_Avg', 'Filter_Type'],
    
    'transmission_health': ['Total_Distance', 'Distance_Since_Fluid_Change', 
                           'Transmission_Temperature', 'Gear_Shifts_Per_100km', 
                           'Harsh_Acceleration_Events', 'Towing_Percentage', 
                           'City_Driving_Percentage', 'Transmission_Type'],
}